### ISSUE TITLE
Duplicated widgets on laravel voyager

### ISSUE THREAD

**Issue by juberjj** [hhxsv5/laravel-s#170]
1. Tell us your software version
![image](https://user-images.githubusercontent.com/16324958/61821346-dc680f00-ae4e-11e9-9249-ab0ef0856515.png)
![image](https://user-images.githubusercontent.com/16324958/61821375-f4d82980-ae4e-11e9-97d3-ee50d10435b0.png)

  
2. Detail description about this issue(error/log)
I have this page developed using Voyager, if I use swooletw server the menu on the left does not render and if I use laravel-s, on refresh, the widget elements gets duplicated

![image](https://user-images.githubusercontent.com/16324958/61821613-83e54180-ae4f-11e9-9e3b-749dbba6dd96.png)

**Comment by hhxsv5** [comment]
Yeah, you need to re-register [Arrilot\Widgets\ServiceProvider](https://github.com/arrilot/laravel-widgets/blob/master/src/ServiceProvider.php#L32).
[Appending widget to group](https://github.com/arrilot/laravel-widgets/blob/master/src/WidgetGroup.php#L270) is dangerous, because `WidgetGroupCollection` instance is singleton and always kept in memory under Swoole mode. 

See [here](https://github.com/hhxsv5/laravel-s/blob/master/KnownIssues.md#use-package-the-control-groupvoyager).

**Comment by juberjj** [comment]
Thanks a lot @hhxsv5 , that did the job just fine, you're the greatest. :+1: 

I've saw the same behavior with nova for the class cards and list, I did re-register the package but the same behaviour occurs. Am I missing or doing something silly here?

![image](https://user-images.githubusercontent.com/16324958/61848007-82923400-aea4-11e9-9812-c18c9786a574.png)

**Comment by hhxsv5** [comment]
@juberjj Try to clear the cache of config ?

```shell
php artisan config:clear
bin/laravels restart
```

**Comment by hhxsv5** [comment]
Sorry, I have not used Nova, and it's not an open source project, I can't know what went wrong.
It is recommended that you track the code to find out where the widget was created and find the singleton. If the singleton is registered in the ServiceProvider, it will be reset by `register_providers`. In other cases,  you can write a [Cleaner](https://github.com/hhxsv5/laravel-s#important-notices) to reset the singleton.

**Comment by juberjj** [comment]
Fantastic will do so, again @hhxsv5 , thank you so much for the assistance given, very much appreciated.
